spring:
  config:
    import: optional:file:/Users/joser.vazquez/config-apps/portal-facturacion/configuracion-general.yml
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:facturacion_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:ricardo}
    password: ${DB_PASSWORD:Ricardo16}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:V7x9K2mP8qR4sT6wY1nB3cD5eF7gH9jL0kM2pQ4rS6uWOso}
    expiration-ms: ${JWT_EXPIRATION_MS:1800000}
    issuer: ${JWT_ISSUER:portal-facturacion}
    audience: ${JWT_AUDIENCE:portal-facturacion-api}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
  correo:
    ruta-layouts: ${CORREO_RUTA_LAYOUTS:/Users/joser.vazquez/config-apps/portal-facturacion}

management:
  endpoint:
    health:
      show-details: always
