CREATE TABLE IF NOT EXISTS factura (
  id_factura BIGINT AUTO_INCREMENT PRIMARY KEY,
  folio VARCHAR(30) NOT NULL,
  serie VARCHAR(10) NULL,
  fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cliente VARCHAR(255) NULL,
  rfc VARCHAR(13) NOT NULL,
  razon_social VARCHAR(255) NOT NULL,
  no_ticket VARCHAR(30) NOT NULL,
  subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  impuesto DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  total DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  estatus VARCHAR(20) NOT NULL DEFAULT 'Cargada',
  uuid VARCHAR(36) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_factura_serie_folio UNIQUE (serie, folio),
  CONSTRAINT uq_factura_uuid UNIQUE (uuid),
  INDEX idx_factura_folio (folio),
  INDEX idx_factura_fecha (fecha),
  INDEX idx_factura_rfc (rfc),
  INDEX idx_factura_no_ticket (no_ticket),
  INDEX idx_factura_estatus (estatus)
);
